spring:
  datasource:
    #124.222.39.14
    url: jdbc:mysql://124.222.39.14:3306/vue-blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: zf_card
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

